add mac pycharm dev
FederatedAI/DOC-CHN pull request #5
Opened 2020-07-03 08:28 UTC by huajinghua

花京华 教程类/ MAC下使用PyCharm进行开发和调试fate.md

2020-07-03 08:59 UTC, tanmc123 requested changes
提交时，需要把.idea的内容全部去掉。

整篇文章内容较少，建议补充一些内容，如调试过程更详细的展示等，可以加截图，如果markdown格式不方便加图，可以使用其他文件格式，如pdf，上传。

2020-07-03 08:59 UTC, tanmc123 commented on .idea/DOC-CHN.iml
> +</module>
请把ide的解析文件（.idea/下的）所以文件去掉

2020-07-03 08:59 UTC, tanmc123 commented on 有奖征集活动/教程类/MAC下使用PyCharm进行开发和调试fate.md
> +   设置之后，在debug模式下启动task_executor.py文件，并在具体的算法模块加入断点即可开始debug了
想要debug，只需要使用debug模式启动fate-flow，然后利用fate-flow接口启动任务即可，无需使用到task_executor

2020-07-03 09:09 UTC, huajinghua commented on 有奖征集活动/教程类/MAC下使用PyCharm进行开发和调试fate.md
> +   设置之后，在debug模式下启动task_executor.py文件，并在具体的算法模块加入断点即可开始debug了
哈哈，试过直接用fate-flowdebug, 但是我这边debug始终进不去，所以提供另一种解决办法

2020-07-03 09:13 UTC, huajinghua commented on .idea/DOC-CHN.iml
> +</module>
好的

2020-07-31 14:21 UTC, chengY666 commented
在线推理增加模型管理服务及分布式配置功能

在实际生产中使用Fate框架时，往往会涉及到很多团队之间的合作，就会遇到各种问题。下面先总结一下使用fate_serving遇到的问题。

遇到的问题
1、	训练环境和在线推理（生产）环境网络不通，无法将模型导入到推理环境。
2、	发布或者绑定模型在server.conf配置文件中配置所有的serving-server的节点，因为训练环境和推理可能处于不同的网络环境中，这其中涉及交互的机器越多，出现错误的可能性也就越大。
3、	推理服务扩容时还需进行load和bind 操作。

需要功能
1、	下线（禁止调用）某个已上线的模型。
2、	好多配置其实是冗余的，应该有分布式配置的功能。

Model_manager功能
1、	server节点启动时，主动去model_manager拉取所有已经上线的模型。
应用场景：扩容就不需要再进行load和bind 操作。
2、	模型更新后（fate_flow发布新模型到推理服务、下线某个模型等），主动通知server节点变更模型状态。
应用场景：实现下线（禁止调用）某个已上线的模型等。
3、	model_manager可以从本地加载模型文件。
应用场景：训练环境和推理环境网络不通问题。
4、	fate_flow只与model_manager交互，不同的网络环境之间交互的次数及机器越少，出现的错误的可能性也就越少。



config功能
1、	分布式配置功能。

2020-08-05 08:14 UTC, merged